runtime: nodejs
env: flex

env_variables:
  NODE_ENV: 'production'

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.5

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

network:
  session_affinity: true

handlers:
  - url: /.*
    script: auto
